'use client'

import { useEffect,useState } from 'react'
import { useParams } from 'next/navigation'
import { CalendarDays, Camera, MapPin, Trophy } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { tripApi } from '@/services/tabitrace-api'

export default function PublicSharePage(){const params=useParams<{token:string}>();const[data,setData]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{tripApi.publicShare(params.token).then(setData).catch((e:any)=>setError(e?.message||'分享链接无效'))},[params.token]);return <main><SiteHeader/><section className="mx-auto max-w-5xl px-5 py-12 sm:px-8">{error?<div className="rounded-2xl bg-vermilion/10 p-5 text-sm text-vermilion">{error}</div>:!data?<div className="text-sm text-black/45">正在读取旅迹分享…</div>:<><p className="text-sm font-medium text-vermilion">UNLISTED TRAVEL STORY</p><h1 className="mt-2 font-serif text-5xl">{data.trip.title}</h1><p className="mt-3 text-sm text-black/45">来自 {data.ownerNickname} 的旅迹分享</p><div className="mt-8 grid gap-4 sm:grid-cols-4"><Stat icon={<CalendarDays size={17}/>} value={String(data.summary.days)} label="天"/><Stat icon={<MapPin size={17}/>} value={String(data.summary.places)} label="地点"/><Stat icon={<Camera size={17}/>} value={String(data.summary.photos)} label="照片"/><Stat icon={<Trophy size={17}/>} value={String(data.summary.achievements)} label="成就"/></div><div className="mt-8 rounded-[28px] border border-black/[0.07] bg-white/50 p-6"><h2 className="font-serif text-3xl">旅行时间轴</h2><div className="mt-5 space-y-4">{data.timeline?.map((day:any)=><div key={day.date} className="rounded-2xl bg-black/[0.025] p-4"><div className="text-xs font-medium text-vermilion">{day.date}</div>{day.items?.map((item:any)=><div key={item.checkin.id} className="mt-3"><div className="font-medium">{item.checkin.placeName}</div><div className="mt-1 text-xs leading-6 text-black/45">{item.checkin.note}</div></div>)}</div>)}</div></div></>}</section></main>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="rounded-2xl border border-black/[0.07] bg-white/50 p-4"><div className="text-vermilion">{icon}</div><div className="mt-4 font-serif text-3xl">{value}</div><div className="text-xs text-black/40">{label}</div></div>}
