'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { authApi } from '@/services/tabitrace-api'

export default function RegisterPage(){const router=useRouter();const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[nickname,setNickname]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await authApi.register({email,password,nickname});setDone(true);setTimeout(()=>router.push('/trips/new'),450)}catch(e:any){setError(e?.message||'注册失败')}finally{setBusy(false)}};return <main><SiteHeader/><section className="mx-auto max-w-3xl px-5 py-14 sm:px-8"><div className="text-center"><p className="text-sm font-bold text-warm">CREATE ACCOUNT</p><h1 className="mt-3 font-serif text-5xl">从下一段旅行开始，认真收藏生活。</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-black/50">创建账号后，你的旅行、打卡、照片、时间轴和分享成果都会保存在同一个旅迹里。</p></div><form onSubmit={submit} className="mx-auto mt-9 max-w-xl warm-card p-7 sm:p-9"><div className="grid gap-4"><label><span className="text-sm">昵称</span><input required value={nickname} onChange={e=>setNickname(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-paper px-4 py-3.5 outline-none focus:border-warm/50"/></label><label><span className="text-sm">邮箱</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-paper px-4 py-3.5 outline-none focus:border-warm/50"/></label><label><span className="text-sm">密码</span><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-paper px-4 py-3.5 outline-none focus:border-warm/50"/></label></div>{error&&<div className="mt-4 rounded-xl bg-warm/10 px-4 py-3 text-xs text-warm">{error}</div>}<button disabled={busy} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3.5 text-sm font-bold text-white disabled:opacity-60">{done?<><CheckCircle2 size={17}/> 注册成功</>:busy?'正在创建账号…':<>创建账号 <ArrowRight size={16}/></>}</button><p className="mt-5 text-center text-xs text-black/40">已有账号？ <Link href="/login" className="font-bold text-warm">登录</Link></p></form></section></main>}
