'use client'

import { useEffect,useState } from 'react'
import { Check, CreditCard, Sparkles } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { tripApi, type TripView } from '@/services/tabitrace-api'

const free=['创建 1 次旅行','全球自由添加地点','最多 10 个打卡','最多 10 张照片','基础统计与分享卡','TabiTrace 水印']
const pro=['无限打卡','更多照片','完整旅行地图','高级统计与东京官方内容','高清分享图与旅行视频','高级模板 · 去水印']
export default function PricingPage(){
  const[trip,setTrip]=useState<TripView|null>(null);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('')
  useEffect(()=>{(async()=>{try{const stored=Number(localStorage.getItem('tabitrace-live-trip-id')||0);if(stored){setTrip(await tripApi.get(stored));return}const rows=await tripApi.list();const active=rows.find(t=>t.status!=='ARCHIVED')||rows[0]||null;if(active){localStorage.setItem('tabitrace-live-trip-id',String(active.id));setTrip(active)}}catch{}})()},[])
  const checkout=async()=>{if(!trip){setMsg('请先创建或打开一段旅行');return}setBusy(true);setMsg('');try{const result=await tripApi.checkout(trip.id);if(result?.mock){const latest=await tripApi.get(trip.id);setTrip(latest);setMsg('本地 Mock 支付成功，当前旅行已升级 Pro')}else if(result?.checkoutUrl){window.location.assign(result.checkoutUrl)}else setMsg('Checkout 已创建')}catch(e:any){setMsg(e.message||'无法开始结账')}finally{setBusy(false)}}
  return <main><SiteHeader/><section className="mx-auto max-w-5xl px-5 pb-14 sm:px-8"><div className="text-center"><p className="text-sm font-bold text-warm">TRIP PRO</p><h1 className="mt-3 font-serif text-5xl">免费开始，在真正需要时再升级。</h1><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-black/50">Pro 按单次旅行生效。每一次旅行都拥有独立的 FREE / PRO 状态。</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><Plan title="FREE" price="¥0" items={free}/><div className="relative rounded-[32px] border border-gold/35 bg-[#F3E8D8] p-7 shadow-card"><span className="absolute right-6 top-6 rounded-full bg-gold px-3 py-1 text-[10px] font-semibold text-white">推荐</span><div className="text-xs tracking-[.2em] text-[#8b6a2f]">TRIP PRO</div><div className="mt-4 font-serif text-5xl">¥490</div><div className="mt-1 text-xs text-black/40">/ 单次旅行</div><div className="mt-7 space-y-3">{pro.map(item=><div key={item} className="flex items-center gap-3 text-sm"><Check size={15} className="text-warm"/>{item}</div>)}</div><button onClick={checkout} disabled={busy||trip?.planType==='PRO'} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3.5 text-sm font-medium text-white disabled:opacity-50"><CreditCard size={16}/>{trip?.planType==='PRO'?'当前旅行已是 Pro':busy?'正在打开 Checkout…':'升级当前旅行'}</button>{trip?<p className="mt-3 text-center text-xs text-black/40">当前：{trip.title} · {trip.planType}</p>:<p className="mt-3 text-center text-xs text-black/40">登录并打开一段旅行后即可升级</p>}{msg&&<p className="mt-3 text-center text-xs font-medium text-warm">{msg}</p>}</div></div><div className="mt-8 warm-card p-6"><Sparkles className="text-warm"/><h2 className="mt-4 font-serif text-2xl">在真正产生价值的时候触发付费</h2><p className="mt-2 text-sm leading-7 text-black/50">用户完成第 10 个地点、准备导出高清旅行长图或 1080P Travel Story 时，再提示升级，更符合当前 MVP 商业设计。</p></div></section></main>
}
function Plan({title,price,items}:{title:string;price:string;items:string[]}){return <div className="warm-card p-7"><div className="text-xs tracking-[.2em] text-black/35">{title}</div><div className="mt-4 font-serif text-5xl">{price}</div><div className="mt-8 space-y-3">{items.map(i=><div key={i} className="flex items-center gap-3 text-sm"><Check size={15} className="text-sage"/>{i}</div>)}</div></div>}
