'use client'

import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { Bell, Globe2, Lock, LogOut, Save, UserRound } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { authApi, userApi, type UserView } from '@/services/tabitrace-api'

export default function ProfilePage(){
  const router=useRouter();const[user,setUser]=useState<UserView|null>(null);const[form,setForm]=useState<any>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[saved,setSaved]=useState('')
  useEffect(()=>{userApi.me().then(u=>{setUser(u);setForm({nickname:u.nickname,locale:u.locale||'zh-CN',timezone:u.timezone||'Asia/Tokyo',defaultVisibility:u.defaultVisibility||'PRIVATE',emailNotifications:u.emailNotifications})}).catch((e:any)=>setError(e.message))},[])
  const save=async()=>{setBusy(true);setSaved('');try{const u=await userApi.update(form);setUser(u);setSaved('设置已保存')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const logout=async()=>{setBusy(true);setError('');try{await authApi.logout()}catch{}finally{localStorage.removeItem('tabitrace-live-trip-id');setBusy(false);router.replace('/login')}}
  return <main><SiteHeader/><section className="mx-auto max-w-5xl px-5 pb-12 sm:px-8"><div className="grid gap-6 lg:grid-cols-[300px_1fr]"><aside className="overflow-hidden rounded-[30px] border border-black/[0.06] bg-[#F4E8DA] p-7"><div className="grid h-20 w-20 place-items-center rounded-full bg-warm text-white"><UserRound size={32}/></div><h1 className="mt-5 font-serif text-3xl">{user?.nickname||'旅行中的我'}</h1><p className="mt-2 text-sm text-black/45">{user?.email||'正在读取…'}</p><div className="mt-8 rounded-2xl bg-white/55 p-4 text-xs leading-6 text-black/50">你的语言、时区、默认分享权限与通知偏好会由后端账号设置统一保存。</div></aside><div className="space-y-5">{error&&<div className="rounded-2xl bg-warm/10 p-4 text-sm text-warm">{error}</div>}<Card icon={<UserRound size={18}/>} title="个人资料"><Field label="昵称" value={form.nickname||''} onChange={(v)=>setForm({...form,nickname:v})}/></Card><Card icon={<Globe2 size={18}/>} title="语言与时区"><div className="grid gap-4 sm:grid-cols-2"><Select label="语言" value={form.locale||'zh-CN'} onChange={v=>setForm({...form,locale:v})} options={[['zh-CN','简体中文'],['ja-JP','日本語'],['en-US','English']]}/><Field label="时区" value={form.timezone||''} onChange={v=>setForm({...form,timezone:v})}/></div></Card><Card icon={<Lock size={18}/>} title="隐私与分享"><Select label="新旅行默认可见性" value={form.defaultVisibility||'PRIVATE'} onChange={v=>setForm({...form,defaultVisibility:v})} options={[['PRIVATE','PRIVATE · 仅自己'],['UNLISTED','UNLISTED · 持链接可访问']]}/></Card><Card icon={<Bell size={18}/>} title="通知"><Toggle label="邮件提醒" desc="旅行结束、视频生成完成等事件通过邮件提示。" value={Boolean(form.emailNotifications)} onChange={v=>setForm({...form,emailNotifications:v})}/></Card><div className="flex flex-wrap items-center gap-3"><button onClick={save} disabled={busy} className="warm-button"><Save size={15}/>{busy?'处理中…':'保存设置'}</button><button onClick={logout} disabled={busy} className="inline-flex items-center gap-2 rounded-[13px] border border-black/10 bg-white px-4 py-3 text-xs font-bold text-black/55 hover:text-warm"><LogOut size={14}/>退出登录</button>{saved&&<span className="text-xs font-bold text-sage">{saved}</span>}</div></div></div></section></main>
}
function Card({icon,title,children}:{icon:React.ReactNode;title:string;children:React.ReactNode}){return <section className="warm-card p-6"><div className="flex items-center gap-3 text-warm">{icon}<h2 className="font-serif text-2xl text-ink">{title}</h2></div><div className="mt-5 space-y-4">{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs text-black/40">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-paper px-4 py-3 text-sm outline-none focus:border-warm/50"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="block"><span className="text-xs text-black/40">{label}</span><select value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-black/10 bg-paper px-4 py-3 text-sm outline-none">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Toggle({label,desc,value,onChange}:{label:string;desc:string;value:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!value)} className="flex w-full items-center gap-4 rounded-2xl bg-black/[0.025] p-4 text-left"><div className="min-w-0 flex-1"><div className="text-sm font-medium">{label}</div><div className="mt-1 text-xs leading-5 text-black/40">{desc}</div></div><div className={`relative h-6 w-11 rounded-full transition ${value?'bg-warm':'bg-black/15'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></div></button>}
