'use client'
import Link from 'next/link'
import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, LockKeyhole, Mail } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { authApi } from '@/services/tabitrace-api'

export default function LoginPage(){const router=useRouter();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await authApi.login({email,password});const next=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('next'):null;router.push(next&&next.startsWith('/')&&!next.startsWith('//')?next:'/trips')}catch(e:any){setError(e?.message||'登录失败，请检查邮箱和密码')}finally{setBusy(false)}};return <main><SiteHeader/><section className="mx-auto grid min-h-[78vh] max-w-6xl items-center gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[1fr_.88fr]"><div className="relative min-h-[520px] overflow-hidden rounded-[34px] shadow-card"><img src="/images/hero-scenery.jpg" alt="东京夕阳" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-8 text-white"><p className="text-xs font-bold tracking-[.18em] text-white/60">WELCOME BACK</p><h1 className="mt-3 max-w-xl font-serif text-5xl leading-tight">继续记录，那些值得回看的旅程。</h1><p className="mt-4 max-w-lg text-sm leading-7 text-white/70">地图、照片、时间和一句话，会在旅迹里重新连成完整的旅行故事。</p></div></div><form onSubmit={submit} className="warm-card p-7 sm:p-9"><p className="text-xs font-bold tracking-[.18em] text-warm">SIGN IN</p><h2 className="mt-2 font-serif text-4xl">登录旅迹</h2><div className="mt-7 space-y-4"><label className="block"><span className="text-sm">邮箱</span><div className="relative mt-2"><Mail size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-black/30"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="w-full rounded-xl border border-black/10 bg-paper py-3.5 pl-11 pr-4 outline-none focus:border-warm/50"/></div></label><label className="block"><span className="text-sm">密码</span><div className="relative mt-2"><LockKeyhole size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-black/30"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required className="w-full rounded-xl border border-black/10 bg-paper py-3.5 pl-11 pr-4 outline-none focus:border-warm/50"/></div></label></div>{error&&<div className="mt-4 rounded-xl bg-warm/10 px-4 py-3 text-xs text-warm">{error}</div>}<button disabled={busy} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-ink px-4 py-3.5 text-sm font-bold text-white disabled:opacity-60">{busy?'正在登录…':<>登录 <ArrowRight size={16}/></>}</button><p className="mt-5 text-center text-xs text-black/40">还没有账号？ <Link href="/register" className="font-bold text-warm">创建账号</Link></p></form></section></main>}
