'use client'

import Link from 'next/link'
import { useEffect,useState } from 'react'
import { useParams } from 'next/navigation'
import { Archive, ArchiveRestore, ArrowRight, CalendarDays, Camera, MapPin, Route, Sparkles, Trophy } from 'lucide-react'
import { SiteHeader } from '@/components/common/SiteHeader'
import { LiveTripSubnav } from '@/components/trip/LiveTripSubnav'
import { tripApi, type TripSummary, type TripView } from '@/services/tabitrace-api'

export default function TripPage(){
  const params=useParams<{id:string}>();const id=Number(params.id);const[trip,setTrip]=useState<TripView|null>(null);const[summary,setSummary]=useState<TripSummary|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const changeArchive=async()=>{if(!trip)return;setBusy(true);setError('');try{const next=trip.status==='ARCHIVED'?await tripApi.unarchive(id):await tripApi.archive(id);setTrip(next);setSummary(await tripApi.summary(id))}catch(e:any){setError(e?.message||'操作失败')}finally{setBusy(false)}}
  useEffect(()=>{localStorage.setItem('tabitrace-live-trip-id',String(id));Promise.all([tripApi.get(id),tripApi.summary(id)]).then(([t,s])=>{setTrip(t);setSummary(s)}).catch((e:any)=>setError(e?.message||'加载失败'))},[id])
  return <main><SiteHeader/><section className="mx-auto max-w-[1180px] px-5 pb-12 sm:px-8">{error?<div className="rounded-2xl bg-warm/10 p-5 text-sm text-warm">{error}</div>:!trip?<div className="text-sm text-black/45">正在读取旅行…</div>:<>
    <div className="relative overflow-hidden rounded-[30px] shadow-card"><img src={trip.coverImage||'/images/cover.jpg'} alt={trip.title} className="h-[300px] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-white sm:p-9"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-bold backdrop-blur">{trip.destinationName}</span><span className="rounded-full bg-warm px-3 py-1 text-[10px] font-bold">{trip.planType}</span></div><h1 className="mt-4 font-serif text-4xl sm:text-5xl">{trip.title}</h1><p className="mt-2 text-sm text-white/75">{trip.startDate} — {trip.endDate} · {trip.peopleCount} 人同行</p></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><LiveTripSubnav tripId={id}/><button disabled={busy} onClick={changeArchive} className="mt-7 inline-flex items-center gap-2 rounded-full border border-black/10 bg-white/55 px-4 py-2 text-xs font-bold text-black/55 transition hover:border-warm/30 hover:text-warm disabled:opacity-50">{trip.status==='ARCHIVED'?<ArchiveRestore size={14}/>:<Archive size={14}/>} {trip.status==='ARCHIVED'?'取消归档':'归档旅行'}</button></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Stat icon={<CalendarDays/>} value={String(summary?.days??'-')} label="天"/><Stat icon={<MapPin/>} value={String(summary?.places??'-')} label="地点"/><Stat icon={<Camera/>} value={String(summary?.photos??'-')} label="照片"/><Stat icon={<Route/>} value={`${summary?.explorationRate??0}%`} label="探索度"/><Stat icon={<Trophy/>} value={String(summary?.achievements??'-')} label="成就"/><Stat icon={<Sparkles/>} value={trip.status} label="状态"/></div>
    <div className="mt-7 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><div className="warm-card p-6"><p className="text-xs font-bold tracking-[.15em] text-warm">TRAVEL READINESS</p><h2 className="mt-2 font-serif text-3xl">成果准备度</h2><p className="mt-2 text-sm text-black/45">由真实打卡、照片和每日记录自动计算。</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Mini value={String(summary?.readiness.recordedDays??0)} label="有记录天数"/><Mini value={String(summary?.readiness.featuredPhotos??0)} label="精选照片"/><Mini value={summary?.readiness.videoReady?'READY':'WAIT'} label="旅行视频"/></div></div><div className="rounded-[28px] bg-[#F2E4D4] p-6"><p className="text-xs font-bold tracking-[.15em] text-warm">NEXT</p><h2 className="mt-2 font-serif text-3xl">继续留下旅迹</h2><p className="mt-3 text-sm leading-6 text-black/50">添加行程、完成打卡、上传照片，最后生成分享图和旅行视频。</p><Link href={`/trips/${id}/map`} className="mt-6 warm-button">进入地图与时间轴 <ArrowRight size={14}/></Link></div></div>
  </>}</section></main>
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="warm-card p-4"><div className="text-warm">{icon}</div><div className="mt-4 font-serif text-2xl">{value}</div><div className="text-[10px] text-black/40">{label}</div></div>}
function Mini({value,label}:{value:string;label:string}){return <div className="rounded-2xl bg-[#F8F2EA] p-4"><div className="font-serif text-2xl text-warm">{value}</div><div className="mt-1 text-xs text-black/40">{label}</div></div>}
